export default ROUTES = {

  // Account
  LOGGED_IN: 'LOGGED_IN',
  REGISTERED_PROVIDER: 'REGISTERED_PROVIDER',
  LOGGED_IN_PROVIDER: 'LOGGED_IN_PROVIDER',


  // Categories
  FETCHED_CATEGORIES: 'FETCHED_CATEGORIES',
  FETCHED_PROVIDERS_BY_CATEGORY: 'FETCHED_PROVIDERS_BY_CATEGORY',
};